spring:
  config:
    import: aws-secretsmanager:resident_meeting

  application:
    name: user-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/resident
    username: root
    password: zerobase

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans

token:
  secret: ${token_secret}
  expiration: ${token_expiration_time}