spring:
  config:
    import: aws-secretsmanager:resident_meeting

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${db_host}:3306/resident
    username: ${db_username}
    password: ${db_password}
    h2:
      console:
        enabled: true
        path: /h2-console
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans

token:
  secret: ${token_secret}
  expiration: ${token_expiration}